routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Exception routes
Route::get('exception/index', 'ExceptionController@index');

Route::get('/welcome', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', function () { return redirect('login'); });
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'check_user_is_client']], function () {
    Route::get('/shopcart', 'ShopCartController@index')->name('shopcart.index');    
    Route::get('/shopcart/list/{id}', 'ShopCartController@list')->name('shopcart.list');        
    Route::get('/shopcart/show/{id}', 'ShopCartController@show')->name('shopcart.show');    
    Route::get('/shopcart/pdf/{id}', 'ShopCartController@pdf')->name('shopcart.pdf');
    Route::get('/payment', 'PaymentController@pay');
    Route::post('/voucher', 'VoucherController@register');
    Route::get('/article/presentation/{ids}', 'ArticleController@getByPresentation');
});

  

Route::group(['middleware' => ['auth', 'check_user_is_admin']], function () {

    Route::get('/register',  'UsersController@create')->name('register');
    Route::post('/register', 'UsersController@register');
    Route::resource('user', 'UsersController');  
    Route::resource('client', 'ClientController')->parameters([
        'client' => 'email'
    ]);    

    Route::prefix('menu')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menu');
        Route::get('/create', 'Admin\MenuController@create')->name('menu/create');
        Route::get('/edit/{id}', 'Admin\MenuController@edit')->name('menu/edit/id');
        Route::get('/get/{id}', 'Admin\MenuController@get');
        Route::get('/recursive/', 'Admin\MenuController@recursive');
        Route::get('/children/{id}', 'Admin\MenuController@children');
        Route::post('/store', 'Admin\MenuController@store');
        Route::put('/', 'Admin\MenuController@update');
        Route::delete('/{id}', 'Admin\MenuController@destroy');    
    });
    
    Route::prefix('role')->group(function () {
        Route::get('/', 'Admin\RoleController@index')->name('role');
       //Route::get('/', 'Admin\RoleController@get');    
    });

    Route::prefix('voucher')->group(function () {
        Route::get('/', 'VoucherController@index')->name('voucher.index');
        Route::get('/{id}', 'VoucherController@show')->name('voucher.show');
    });
        
    Route::prefix('replacement')->group(function () {
        Route::get('/', 'ReplacementController@index')->name('replacement.index');
        Route::get('/create', 'ReplacementController@create')->name('replacement.create');
        Route::get('/show/{replacement}', 'ReplacementController@show')->name('replacement.show');
        Route::get('/edit/{replacement}', 'ReplacementController@edit')->name('replacement.edit');    
        Route::post('/', 'ReplacementController@store')->name('replacement.store');
        Route::put('/{replacement}', 'ReplacementController@update')->name('replacement.update');
        Route::post('/detail', 'ReplacementDetailController@store')->name('replacement.detail.store');
        Route::put('/detail/{replacementDetail}', 'ReplacementDetailController@update')->name('replacement.detail.update');
        Route::delete('/detail/{replacementDetail}', 'ReplacementDetailController@destroy')->name('replacement.detail.destroy');
    });
    
    Route::prefix('movement')->group(function () {
      Route::get('/', 'MovementController@index')->name('movement.index');
      Route::get('/show/{movement}', 'MovementController@show')->name('movement.show');    
    });
    
    Route::prefix('stock')->group(function () {
      Route::get('/', 'StockController@index')->name('stock.index');    
    });
    
    Route::prefix('article')->group(function () {
      Route::get('/', 'ArticleController@index')->name('article.index');
      Route::get('/get', 'ArticleController@get')->name('article.get');      
      Route::get('/search/{value}', 'ArticleController@search')->name('article.search');
      Route::post('/', 'ArticleController@store')->name('article.store');
      Route::put('/{article}', 'ArticleController@update')->name('article.update');
      Route::post('/photo', 'ArticleController@photo')->name('article.photo');
      Route::delete('/{article}', 'ArticleController@destroy')->name('article.destroy');
      Route::put('/restore/{article}', 'ArticleController@restore')->name('article.restore');
    });

    Route::prefix('article-detail')->group(function () {
      Route::get('/{articleId}', 'ArticleDetailController@index')->name('article-detail.index');
      Route::post('/', 'ArticleDetailController@store')->name('article-detail.store');
      Route::delete('/{articleDetail}', 'ArticleDetailController@destroy')->name('article-detail.destroy');
    });
     
});

resources/views/_welcome.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        {{-- @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif --}}
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Laravel
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Docs</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://blog.laravel.com">Blog</a>
                    <a href="https://nova.laravel.com">Nova</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://vapor.laravel.com">Vapor</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
    @if (Auth::user()->is_admin==1)
        <div class="col-12 col-md-4 mb-4 mb-md-0 d-flex justify-content-center grow">            
          <img src="../../img/user.svg" width="50%" style="margin:auto">
        </div>
        <!--div class="col-12 col-md-4 mb-4 mb-md-0 d-flex justify-content-center grow" href="{{route('register')}}">
            <a href="{{route('user.index')}}" class="card text-center w-75 p-5 text-body">
                <img src="../../img/user.svg" width="50%" style="margin:auto">
                Registrar Usuarios
            </a>
        </div>
        <div class="col-12 col-md-4 d-flex justify-content-center grow">
            <a href="{{route('client.index')}}" class="card text-center w-75 p-5 text-body">
                <img src="../../img/user.svg" width="50%" style="margin:auto">
                Registrar Clientes
            </a>
        </div>
        <div class="col-12 col-md-4 d-flex justify-content-center grow">
            <a href="{{route('voucher.index')}}" class="card text-center w-75 p-5 text-body" align="center">
                <img src="../../img/iconmonstr-search-thin.svg" width="50%" style="margin:auto">
                Consultar Compras
            </a>
        </div>
        <div class="col-12 col-md-4 d-flex justify-content-center grow">
            <a href="{{route('replacement.index')}}" class="card text-center w-75 p-5 text-body" align="center">
                <img src="../../img/iconmonstr-search-thin.svg" width="50%" style="margin:auto">
                Reposición
            </a>
        </div>
        <div class="col-12 col-md-4 d-flex justify-content-center grow">
            <a href="{{route('movement.index')}}" class="card text-center w-75 p-5 text-body" align="center">
                <img src="../../img/iconmonstr-search-thin.svg" width="50%" style="margin:auto">
                Movimientos
            </a>
        </div-->
    @else
    
            <div class="col-12 col-md-4 mb-4 mb-md-0 d-flex justify-content-center grow">            
          <img src="../../img/cart.svg" width="50%" style="margin:auto">
        </div>
    
    <!--div class="col-12 col-md-4 mb-4 mb-md-0 d-flex justify-content-center grow" href="{{route('shopcart.index')}}">
            <a href="{{route('shopcart.index')}}" 
               class="card align-center text-center w-75 p-5 text-body"
               style="display:none;"
               id="a_shopcart">              
               <img src="../../img/cart.svg" width="50%" style="margin:auto">
                Carrito de Compra New
            </a>
        </div>
        <div class="col-12 col-md-4 mb-4 mb-md-0 d-flex justify-content-center grow" href="{{route('register')}}">
            <a href="{{route('register')}}" 
               class="card align-center text-center w-75 p-5 text-body"
               style="display:none;"
               id="a_shopcart">              
               <img src="../../img/cart.svg" width="50%" style="margin:auto">
                Carrito de Compra Old
            </a>
        </div>
        <div class="col-12 col-md-4 d-flex justify-content-center grow">
            <a href="#" class="card text-center w-75 p-5 text-body" style="display:none" id="a_list"  align="center">
                <img src="../../img/iconmonstr-search-thin.svg" width="50%" style="margin:auto">
                Consultar Compras
            </a>
        </div-->        
    @endif

    </div>
</div>
@endsection
@section('after_scripts')
  <script src="{{ asset('js/home.js') }}"></script>
  <script>home('{{ Auth::user()->email }}');</script>
@endsection