routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Exception routes
Route::get('exception/index', 'ExceptionController@index');

Route::get('/welcome', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', function () { return redirect('login'); });
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'check_user_is_client']], function () {
    Route::get('/shopcart', 'ShopCartController@index')->name('shopcart.index');    
    Route::get('/shopcart/list/{id}', 'ShopCartController@list')->name('shopcart.list');        
    Route::get('/shopcart/show/{id}', 'ShopCartController@show')->name('shopcart.show');    
    Route::get('/shopcart/pdf/{id}', 'ShopCartController@pdf')->name('shopcart.pdf');
    Route::get('/payment', 'PaymentController@pay');
    Route::post('/voucher', 'VoucherController@register');
    Route::get('/article/presentation/{ids}', 'ArticleController@getByPresentation');
});

  

Route::group(['middleware' => ['auth', 'check_user_is_admin']], function () {

    Route::get('/register',  'UsersController@create')->name('register');
    Route::post('/register', 'UsersController@register');
    Route::resource('user', 'UsersController');  
    Route::resource('client', 'ClientController')->parameters([
        'client' => 'email'
    ]);    

    Route::prefix('menu')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menu');
        Route::get('/create', 'Admin\MenuController@create')->name('menu/create');
        Route::get('/edit/{id}', 'Admin\MenuController@edit')->name('menu/edit/id');
        Route::get('/get/{id}', 'Admin\MenuController@get');
        Route::get('/recursive/', 'Admin\MenuController@recursive');
        Route::get('/children/{id}', 'Admin\MenuController@children');
        Route::post('/store', 'Admin\MenuController@store');
        Route::put('/', 'Admin\MenuController@update');
        Route::delete('/{id}', 'Admin\MenuController@destroy');    
    });
    
    Route::prefix('role')->group(function () {
        Route::get('/', 'Admin\RoleController@index')->name('role');
       //Route::get('/', 'Admin\RoleController@get');    
    });

    Route::prefix('voucher')->group(function () {
        Route::get('/', 'VoucherController@index')->name('voucher.index');
        Route::get('/{id}', 'VoucherController@show')->name('voucher.show');
    });
        
    Route::prefix('replacement')->group(function () {
        Route::get('/', 'ReplacementController@index')->name('replacement.index');
        Route::get('/create', 'ReplacementController@create')->name('replacement.create');
        Route::get('/show/{replacement}', 'ReplacementController@show')->name('replacement.show');
        Route::get('/edit/{replacement}', 'ReplacementController@edit')->name('replacement.edit');    
        Route::post('/', 'ReplacementController@store')->name('replacement.store');
        Route::put('/{replacement}', 'ReplacementController@update')->name('replacement.update');
        Route::post('/detail', 'ReplacementDetailController@store')->name('replacement.detail.store');
        Route::put('/detail/{replacementDetail}', 'ReplacementDetailController@update')->name('replacement.detail.update');
        Route::delete('/detail/{replacementDetail}', 'ReplacementDetailController@destroy')->name('replacement.detail.destroy');
    });
    
    Route::prefix('movement')->group(function () {
      Route::get('/', 'MovementController@index')->name('movement.index');
      Route::get('/show/{movement}', 'MovementController@show')->name('movement.show');    
    });
    
    Route::prefix('stock')->group(function () {
      Route::get('/', 'StockController@index')->name('stock.index');    
    });
    
    Route::prefix('article')->group(function () {
      Route::get('/', 'ArticleController@index')->name('article.index');
      Route::get('/get', 'ArticleController@get')->name('article.get');      
      Route::get('/search/{value}', 'ArticleController@search')->name('article.search');
      Route::post('/', 'ArticleController@store')->name('article.store');
      Route::put('/{article}', 'ArticleController@update')->name('article.update');
      Route::post('/photo', 'ArticleController@photo')->name('article.photo');
      Route::delete('/{article}', 'ArticleController@destroy')->name('article.destroy');
      Route::put('/restore/{article}', 'ArticleController@restore')->name('article.restore');
    });

    Route::prefix('article-detail')->group(function () {
      Route::get('/{articleId}', 'ArticleDetailController@index')->name('article-detail.index');
      Route::post('/', 'ArticleDetailController@store')->name('article-detail.store');
      Route::delete('/{articleDetail}', 'ArticleDetailController@destroy')->name('article-detail.destroy');
    });
     
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'is_admin',
        'password',
        'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setEmailAttribute($email)
    {
        $this->attributes['email'] = strtolower($email);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\User\StoreUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\User;
use Hash;

class UsersController extends Controller
{
    private $roles;

    public function __construct()
    {
        $this->roles = [
            ['name' => 'Usuario', 'value' => false],
            ['name' => 'Administrador', 'value' => true]
        ];
    }

    public function index()
    {
        $users = User::orderBy('name')->paginate(5);
        return view('users.index', compact('users'));
    }

    public function create()
    {
        return view('auth.register', [
            'roles' => $this->roles
        ]);
    }

    public function register(StoreUserRequest $request)
    {
        User::create([
            'name' => $request->name,
            'address' => $request->address,
            'email' => $request->email,
            'is_admin' => !is_null($request->is_admin),
            'password' => Hash::make($request->password),
        ]);
        return redirect()->action('UsersController@index')->with('success', 'El usuario fue creado');
    }

    public function show(User $user)
    {
        return view('users.show', [
            'roles' => $this->roles,
            'user' => $user
        ]);
    }

    public function edit(User $user)
    {
        return view('users.edit', [
            'roles' => $this->roles,
            'user' => $user
        ]);
    }

    public function update(User $user, UpdateUserRequest $request)
    {
        $emailIsTaken = User::where('email', $request->email)->whereNotNull('deleted_at')->first();
        $user->name = $request->name ?? $user->name;
        $user->email = $emailIsTaken ? $user->email : $request->email;
        $user->is_admin = !is_null($request->is_admin);
        $user->password = Hash::make($request->password ?? $user->email);
        $user->save();
        session(['success' => 'El usuario fue actualizado']);

        return view('users.edit', [
            'roles' => $this->roles,
            'user' => $user
        ]);
    }

    public function destroy($email)
    {
        $user = User::where('email', $email)->first();
        $user->email = $user->id. " ".$user->email;
        $user->save();
        $user->delete();
        session(['success' => 'El usuario fue eliminado']);
        return redirect()->route('user.index');
    }
}

resources/views/users/partials/form.blade.php
@csrf

<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

    <div class="col-md-6">
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name ?? old('name') }}" {{ isset($readonly) ? "readonly" : null }} autocomplete="name" autofocus >

        @error('name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

    <div class="col-md-6">
        <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email ?? old('email') }}" {{ isset($readonly) ? "readonly" : null }} autocomplete="email">

        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="is_admin" class="col-md-4 text-md-right col-form-label">Rol</label>
    <div class="col-md-6">
        <select name="is_admin" class="form-control" id="is_admin" {{ isset($readonly) ? "readonly" : null }}>
            @foreach($roles as $role)
            <option value="{{$role['value']}}" @isset($user) {{ $user->is_admin == $role['value']  ? "selected" : null }} @endisset>{{$role['name']}}</option>
            @endforeach
        </select>
    </div>
</div>
@if(!isset($readonly))
<div class="form-group row">
    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Contraseña') }}</label>

    <div class="col-md-6">
        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" {{ isset($readonly) ? "readonly" : null }} autocomplete="new-password">

        @error('password')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>
@endif
@if(!isset($readonly))
<div class="form-group row">
    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirmar Contraseña') }}</label>

    <div class="col-md-6">
        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" {{ isset($readonly) ? "readonly" : null }} autocomplete="new-password">
    </div>
</div>
@endif

resources/views/users/partials/modal_delete.blade.php
<div class="modal fade" id="{{ isset($modalId) ? $modalId : 'modalDelete' }}" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="{{ isset($modalId) ? $modalId : 'modalDeleteLabel' }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="{{ isset($modalId) ? $modalId : 'modalDeleteLabel' }}">Eliminar Usario</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body text-center">
          ¿Está seguro de eliminar a este usuario?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
          <form method="POST" action="{{ route('user.destroy', $user->email) }}">
            @method('DELETE')
            @csrf
            <button class="btn btn-primary font-weight-bold">Eliminar</button>
          </form>
        </div>
      </div>
    </div>
  </div>