routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Exception routes
Route::get('exception/index', 'ExceptionController@index');

Route::get('/welcome', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', function () { return redirect('login'); });
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'check_user_is_client']], function () {
    Route::get('/shopcart', 'ShopCartController@index')->name('shopcart.index');    
    Route::get('/shopcart/list/{id}', 'ShopCartController@list')->name('shopcart.list');        
    Route::get('/shopcart/show/{id}', 'ShopCartController@show')->name('shopcart.show');    
    Route::get('/shopcart/pdf/{id}', 'ShopCartController@pdf')->name('shopcart.pdf');
    Route::get('/payment', 'PaymentController@pay');
    Route::post('/voucher', 'VoucherController@register');
    Route::get('/article/presentation/{ids}', 'ArticleController@getByPresentation');
});

  

Route::group(['middleware' => ['auth', 'check_user_is_admin']], function () {

    Route::get('/register',  'UsersController@create')->name('register');
    Route::post('/register', 'UsersController@register');
    Route::resource('user', 'UsersController');  
    Route::resource('client', 'ClientController')->parameters([
        'client' => 'email'
    ]);    

    Route::prefix('menu')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menu');
        Route::get('/create', 'Admin\MenuController@create')->name('menu/create');
        Route::get('/edit/{id}', 'Admin\MenuController@edit')->name('menu/edit/id');
        Route::get('/get/{id}', 'Admin\MenuController@get');
        Route::get('/recursive/', 'Admin\MenuController@recursive');
        Route::get('/children/{id}', 'Admin\MenuController@children');
        Route::post('/store', 'Admin\MenuController@store');
        Route::put('/', 'Admin\MenuController@update');
        Route::delete('/{id}', 'Admin\MenuController@destroy');    
    });
    
    Route::prefix('role')->group(function () {
        Route::get('/', 'Admin\RoleController@index')->name('role');
       //Route::get('/', 'Admin\RoleController@get');    
    });

    Route::prefix('voucher')->group(function () {
        Route::get('/', 'VoucherController@index')->name('voucher.index');
        Route::get('/{id}', 'VoucherController@show')->name('voucher.show');
    });
        
    Route::prefix('replacement')->group(function () {
        Route::get('/', 'ReplacementController@index')->name('replacement.index');
        Route::get('/create', 'ReplacementController@create')->name('replacement.create');
        Route::get('/show/{replacement}', 'ReplacementController@show')->name('replacement.show');
        Route::get('/edit/{replacement}', 'ReplacementController@edit')->name('replacement.edit');    
        Route::post('/', 'ReplacementController@store')->name('replacement.store');
        Route::put('/{replacement}', 'ReplacementController@update')->name('replacement.update');
        Route::post('/detail', 'ReplacementDetailController@store')->name('replacement.detail.store');
        Route::put('/detail/{replacementDetail}', 'ReplacementDetailController@update')->name('replacement.detail.update');
        Route::delete('/detail/{replacementDetail}', 'ReplacementDetailController@destroy')->name('replacement.detail.destroy');
    });
    
    Route::prefix('movement')->group(function () {
      Route::get('/', 'MovementController@index')->name('movement.index');
      Route::get('/show/{movement}', 'MovementController@show')->name('movement.show');    
    });
    
    Route::prefix('stock')->group(function () {
      Route::get('/', 'StockController@index')->name('stock.index');    
    });
    
    Route::prefix('article')->group(function () {
      Route::get('/', 'ArticleController@index')->name('article.index');
      Route::get('/get', 'ArticleController@get')->name('article.get');      
      Route::get('/search/{value}', 'ArticleController@search')->name('article.search');
      Route::post('/', 'ArticleController@store')->name('article.store');
      Route::put('/{article}', 'ArticleController@update')->name('article.update');
      Route::post('/photo', 'ArticleController@photo')->name('article.photo');
      Route::delete('/{article}', 'ArticleController@destroy')->name('article.destroy');
      Route::put('/restore/{article}', 'ArticleController@restore')->name('article.restore');
    });

    Route::prefix('article-detail')->group(function () {
      Route::get('/{articleId}', 'ArticleDetailController@index')->name('article-detail.index');
      Route::post('/', 'ArticleDetailController@store')->name('article-detail.store');
      Route::delete('/{articleDetail}', 'ArticleDetailController@destroy')->name('article-detail.destroy');
    });
     
});

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Http;
use App\Service;
//use App\Client;
use App\Http\Requests\Client\{StoreClientRequest, UpdateClientRequest};
use App\Http\Resources\{ClientCollection, Client as ClientResource};

use Illuminate\Http\Request;

class ClientController extends Controller
{
    public function index()
    {
        $clientsResponse = Service::client()->json();
        $clients = collect($clientsResponse)->paginate(5);
        return view('clients.index', ['clients' => new ClientCollection($clients)]);
    }

    public function create()
    {        
        $states = Service::geoLocationState()->json();
        $zoneTypes = Service::geoLocationZoneType()->json();
        $routeTypes = Service::geoLocationRouteType()->json();
        $domicileTypes = Service::geoLocationDomicileType()->json();    
        return view('clients.create', [            
            'states'         => $states,
            'municipalities' => [],
            'parishes'       => [],
            'zoneTypes'      => $zoneTypes,
            'routeTypes'     => $routeTypes,
            'domicileTypes'  => $domicileTypes
        ]);
    }
    
    public function edit($email)
    {
        $client = Service::client(['email' => $email])->json();
        $states = Service::geoLocationState()->json();
        $municipalities = Service::geoLocationMunicipality($client['state'])->json();
        $parishes = Service::geoLocationParish($client['municipality'])->json();
        $zoneTypes = Service::geoLocationZoneType()->json();
        $routeTypes = Service::geoLocationRouteType()->json();
        $domicileTypes = Service::geoLocationDomicileType()->json();
        return view('clients.edit', [
            'client'         => new ClientResource((object)$client),
            'states'         => $states,
            'municipalities' => $municipalities,
            'parishes'       => $parishes,
            'zoneTypes'      => $zoneTypes,
            'routeTypes'     => $routeTypes,
            'domicileTypes'  => $domicileTypes
        ]);
    }
    
    public function show($email)
    {        
        $client = Service::client(['email' => $email])->json();
        $states = Service::geoLocationState()->json();
        $municipalities = Service::geoLocationMunicipality($client['state'])->json();      
        $parishes = Service::geoLocationParish($client['municipality'])->json();        
        $zoneTypes = Service::geoLocationZoneType()->json();
        $routeTypes = Service::geoLocationRouteType()->json();
        $domicileTypes = Service::geoLocationDomicileType()->json();         
        return view('clients.show', [
            'client'         => new ClientResource((object)$client),
            'states'         => $states,
            'municipalities' => $municipalities,
            'parishes'       => $parishes,
            'zoneTypes'      => $zoneTypes,
            'routeTypes'     => $routeTypes,
            'domicileTypes'  => $domicileTypes
        ]);
    }

    public function store(StoreClientRequest $request)
    {    
        $clientResponse = Service::clientPost($request->except(['_token']));
        if($clientResponse->failed()){           
            return redirect()->route('client.index')->with('error', 'No se pudo crear al cliente');
        }        
        return redirect()->route('client.index')->with('success', 'El cliente fue creado');
    }
    
    public function update(UpdateClientRequest $request, $email)
    {
        $clientResponse = Service::clientPut($email, $request->except(['_token']));
        if($clientResponse->failed()){
            return redirect()->route('client.index')->with('error', 'No se pudo actualizar al cliente');            
        }        
        return redirect()->route('client.index')->with('success', 'El cliente fue actualizado');
    }

    public function destroy($email)
    {        
        $clientResponse = Service::clientDelete($email);
        if($clientResponse->failed()){
            return redirect()->route('client.index')->with('error', 'No se pudo eliminar al cliente');            
        }        
        return redirect()->route('client.index')->with('success', 'El cliente fue eliminado');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')
@section('messages')
    @isset($message)
        @include('layouts.message', ['message' => $message])
    @endisset
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 col-md-6 bg-white shadow p-3">                
                <div class="card-header"> <h4>Registrar Cliente</h4> </div>
                <div class="card-body">
                  <form method="POST" action="{{ route('client.store') }}">
                      @csrf
                      @include('clients.partials.form')
                      <div class="text-center">
                          <a type="buttom" class="btn btn-success" href="{{ route('client.index') }}">Regresar</a>
                              &nbsp;&nbsp;&nbsp;
                          <button class="btn btn-primary">Registrar</button>
                      </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after_scripts')
  <script src="{{ asset('js/Service.js') }}"></script>
  <script src="{{ asset('js/fdsoil/Select.js') }}"></script>
  <script src="{{ asset('js/fdsoil/WaitElement.js') }}"></script>
  <script>

    const municipalitySearch = function (stateId) {

      Service.municipality(stateId).then(response => {
        const eMunicipality = document.getElementById('municipality');
        const eParish = document.getElementById('parish');
        Select.fill(eMunicipality, response, '0', 'Seleccione...', {id:'id', text:'description'});
        Select.fill(eParish, [], '0', 'Seleccione...', {id:'id', text:'description'});
      });

    }

    const parishSearch = function (municipalityId) {

      Service.parish(municipalityId).then(response => {
        const eParish = document.getElementById('parish');
        Select.fill(eParish, response, '0', 'Seleccione...', {id:'id', text:'description'});
      });

    }


  </script>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Editar Cliente') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('client.update', $client->email) }}">
                        @csrf
                        @method('PUT')
                        @include('clients.partials.form', ['client' => $client])
                        <div class="form-group row justify-content-center">
                            <a type="buttom" class="btn btn-success" href="{{ route('client.index') }}">Regresar</a>
                            &nbsp;&nbsp;&nbsp;
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('after_scripts')
  <script src="{{ asset('js/Service.js') }}"></script>
  <script src="{{ asset('js/fdsoil/Select.js') }}"></script>
  <script src="{{ asset('js/fdsoil/WaitElement.js') }}"></script>
  <script>

    const municipalitySearch = function (stateId) {

      Service.municipality(stateId).then(response => {
        const eMunicipality = document.getElementById('municipality');
        const eParish = document.getElementById('parish');
        Select.fill(eMunicipality, response, '0', 'Seleccione...', {id:'id', text:'description'});
        Select.fill(eParish, [], '0', 'Seleccione...', {id:'id', text:'description'});
      });

    }

    const parishSearch = function (municipalityId) {

      Service.parish(municipalityId).then(response => {
        const eParish = document.getElementById('parish');
        Select.fill(eParish, response, '0', 'Seleccione...', {id:'id', text:'description'});
      });

    }

  </script>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 d-flex flex-column align-items-center bg-white shadow">
                <div class="d-flex w-100 justify-content-between align-items-center p-3">
                    <h1 class="mb-0">Clientes</h1>
                    <a href="{{ route('client.create') }}" class="btn btn-primary font-weight-bold">Nuevo</a>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr class="table-success text-center">
                            <th scope="col">Tipo</th>
                            <th scope="col">Cédula / Rif</th>
                            <th scope="col">Nombre / Razón Social</th>                            
                            <th scope="col">Teléfono</th>
                            <th scope="col">Email</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($clients as $client)
                        <tr>
                            <td>{{ $client['type'] ? 'Natural':'Jurídica' }}</td>                            
                            <td>{{ $client['ced_rif'] }}</td>
                            <td>{{ $client['business_name'] }}</td>
                            <td>{{ $client['phone'] }}</td>
                            <td>{{ $client['email'] }}</td>
                            <td class="d-flex justify-content-around">
                                <a href="{{ route('client.show', $client['email']) }}" class="btn btn-success font-weight-bold">Ver</a>
                                <a href="{{ route('client.edit', $client['email']) }}" class="btn btn-primary font-weight-bold">Modificar</a>
                                <button class="btn btn-danger font-weight-bold" 
                                        data-toggle="modal"
                                        data-target="{{'#clientDeleteModal'.$client['id']}}">Borrar</button>
                                @include('clients.partials.modal_delete', ['modalId' => 'clientDeleteModal'.$client['id']])
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

                {!! $clients->links() !!}

            </div>
        </div>
    </div>
@endsection

resources/views/clients/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Ver Cliente') }}</div>
                <div class="card-body">
                        @include('clients.partials.form', ['client' => $client, 'readonly' => true])
                        <div class="form-group row justify-content-center">
                            <a type="buttom" class="btn btn-success" href="{{ route('client.index') }}">Regresar</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('after_scripts')
@endsection