routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Exception routes
Route::get('exception/index', 'ExceptionController@index');

Route::get('/welcome', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', function () { return redirect('login'); });
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'check_user_is_client']], function () {
    Route::get('/shopcart', 'ShopCartController@index')->name('shopcart.index');    
    Route::get('/shopcart/list/{id}', 'ShopCartController@list')->name('shopcart.list');        
    Route::get('/shopcart/show/{id}', 'ShopCartController@show')->name('shopcart.show');    
    Route::get('/shopcart/pdf/{id}', 'ShopCartController@pdf')->name('shopcart.pdf');
    Route::get('/payment', 'PaymentController@pay');
    Route::post('/voucher', 'VoucherController@register');
    Route::get('/article/presentation/{ids}', 'ArticleController@getByPresentation');
});

  

Route::group(['middleware' => ['auth', 'check_user_is_admin']], function () {

    Route::get('/register',  'UsersController@create')->name('register');
    Route::post('/register', 'UsersController@register');
    Route::resource('user', 'UsersController');  
    Route::resource('client', 'ClientController')->parameters([
        'client' => 'email'
    ]);    

    Route::prefix('menu')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menu');
        Route::get('/create', 'Admin\MenuController@create')->name('menu/create');
        Route::get('/edit/{id}', 'Admin\MenuController@edit')->name('menu/edit/id');
        Route::get('/get/{id}', 'Admin\MenuController@get');
        Route::get('/recursive/', 'Admin\MenuController@recursive');
        Route::get('/children/{id}', 'Admin\MenuController@children');
        Route::post('/store', 'Admin\MenuController@store');
        Route::put('/', 'Admin\MenuController@update');
        Route::delete('/{id}', 'Admin\MenuController@destroy');    
    });
    
    Route::prefix('role')->group(function () {
        Route::get('/', 'Admin\RoleController@index')->name('role');
       //Route::get('/', 'Admin\RoleController@get');    
    });

    Route::prefix('voucher')->group(function () {
        Route::get('/', 'VoucherController@index')->name('voucher.index');
        Route::get('/{id}', 'VoucherController@show')->name('voucher.show');
    });
        
    Route::prefix('replacement')->group(function () {
        Route::get('/', 'ReplacementController@index')->name('replacement.index');
        Route::get('/create', 'ReplacementController@create')->name('replacement.create');
        Route::get('/show/{replacement}', 'ReplacementController@show')->name('replacement.show');
        Route::get('/edit/{replacement}', 'ReplacementController@edit')->name('replacement.edit');    
        Route::post('/', 'ReplacementController@store')->name('replacement.store');
        Route::put('/{replacement}', 'ReplacementController@update')->name('replacement.update');
        Route::post('/detail', 'ReplacementDetailController@store')->name('replacement.detail.store');
        Route::put('/detail/{replacementDetail}', 'ReplacementDetailController@update')->name('replacement.detail.update');
        Route::delete('/detail/{replacementDetail}', 'ReplacementDetailController@destroy')->name('replacement.detail.destroy');
    });
    
    Route::prefix('movement')->group(function () {
      Route::get('/', 'MovementController@index')->name('movement.index');
      Route::get('/show/{movement}', 'MovementController@show')->name('movement.show');    
    });
    
    Route::prefix('stock')->group(function () {
      Route::get('/', 'StockController@index')->name('stock.index');    
    });
    
    Route::prefix('article')->group(function () {
      Route::get('/', 'ArticleController@index')->name('article.index');
      Route::get('/get', 'ArticleController@get')->name('article.get');      
      Route::get('/search/{value}', 'ArticleController@search')->name('article.search');
      Route::post('/', 'ArticleController@store')->name('article.store');
      Route::put('/{article}', 'ArticleController@update')->name('article.update');
      Route::post('/photo', 'ArticleController@photo')->name('article.photo');
      Route::delete('/{article}', 'ArticleController@destroy')->name('article.destroy');
      Route::put('/restore/{article}', 'ArticleController@restore')->name('article.restore');
    });

    Route::prefix('article-detail')->group(function () {
      Route::get('/{articleId}', 'ArticleDetailController@index')->name('article-detail.index');
      Route::post('/', 'ArticleDetailController@store')->name('article-detail.store');
      Route::delete('/{articleDetail}', 'ArticleDetailController@destroy')->name('article-detail.destroy');
    });
     
});

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Http;
use App\Service;
//use App\Client;
use App\Http\Requests\Client\{StoreClientRequest, UpdateClientRequest};
use App\Http\Resources\{ClientCollection, Client as ClientResource};

use Illuminate\Http\Request;

class ClientController extends Controller
{
    public function index()
    {
        $clientsResponse = Service::client()->json();
        $clients = collect($clientsResponse)->paginate(5);
        return view('clients.index', ['clients' => new ClientCollection($clients)]);
    }

    public function create()
    {        
        $states = Service::geoLocationState()->json();
        $zoneTypes = Service::geoLocationZoneType()->json();
        $routeTypes = Service::geoLocationRouteType()->json();
        $domicileTypes = Service::geoLocationDomicileType()->json();    
        return view('clients.create', [            
            'states'         => $states,
            'municipalities' => [],
            'parishes'       => [],
            'zoneTypes'      => $zoneTypes,
            'routeTypes'     => $routeTypes,
            'domicileTypes'  => $domicileTypes
        ]);
    }
    
    public function edit($email)
    {
        $client = Service::client(['email' => $email])->json();
        $states = Service::geoLocationState()->json();
        $municipalities = Service::geoLocationMunicipality($client['state'])->json();
        $parishes = Service::geoLocationParish($client['municipality'])->json();
        $zoneTypes = Service::geoLocationZoneType()->json();
        $routeTypes = Service::geoLocationRouteType()->json();
        $domicileTypes = Service::geoLocationDomicileType()->json();
        return view('clients.edit', [
            'client'         => new ClientResource((object)$client),
            'states'         => $states,
            'municipalities' => $municipalities,
            'parishes'       => $parishes,
            'zoneTypes'      => $zoneTypes,
            'routeTypes'     => $routeTypes,
            'domicileTypes'  => $domicileTypes
        ]);
    }
    
    public function show($email)
    {        
        $client = Service::client(['email' => $email])->json();
        $states = Service::geoLocationState()->json();
        $municipalities = Service::geoLocationMunicipality($client['state'])->json();      
        $parishes = Service::geoLocationParish($client['municipality'])->json();        
        $zoneTypes = Service::geoLocationZoneType()->json();
        $routeTypes = Service::geoLocationRouteType()->json();
        $domicileTypes = Service::geoLocationDomicileType()->json();         
        return view('clients.show', [
            'client'         => new ClientResource((object)$client),
            'states'         => $states,
            'municipalities' => $municipalities,
            'parishes'       => $parishes,
            'zoneTypes'      => $zoneTypes,
            'routeTypes'     => $routeTypes,
            'domicileTypes'  => $domicileTypes
        ]);
    }

    public function store(StoreClientRequest $request)
    {    
        $clientResponse = Service::clientPost($request->except(['_token']));
        if($clientResponse->failed()){           
            return redirect()->route('client.index')->with('error', 'No se pudo crear al cliente');
        }        
        return redirect()->route('client.index')->with('success', 'El cliente fue creado');
    }
    
    public function update(UpdateClientRequest $request, $email)
    {
        $clientResponse = Service::clientPut($email, $request->except(['_token']));
        if($clientResponse->failed()){
            return redirect()->route('client.index')->with('error', 'No se pudo actualizar al cliente');            
        }        
        return redirect()->route('client.index')->with('success', 'El cliente fue actualizado');
    }

    public function destroy($email)
    {        
        $clientResponse = Service::clientDelete($email);
        if($clientResponse->failed()){
            return redirect()->route('client.index')->with('error', 'No se pudo eliminar al cliente');            
        }        
        return redirect()->route('client.index')->with('success', 'El cliente fue eliminado');
    }
}

resources/views/clients/partials/form.blade.php
<div class="form-group row">
    <div class="col-sm-12">
        <label for="email">Correo electrònico del cliente</label>
        <input type="text"
               class="form-control @error('email') is-invalid @enderror"
               id="email"
               name="email"
               placeholder="Email"
               value="{{ isset($client) && $client->email ? $client->email : old('email') }}"               
               {{ isset($readonly) ? "readonly" : null }}>
        @error('email')
            <span class="invalid-feedback" role="alert"> isset($client)
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <div class="col-sm-12">
        <label for="type">Tipo de persona:</label><br/>       
        <input type="radio"
               id="id_type_natural"
               name="type"               
               value="t" {{ isset($client) && $client->type ? 'checked' : '' }}> Natural
        <input type="radio"
              id="id_type_juridica"
              name="type"              
              value="f" {{ isset($client) && !$client->type ? 'checked' : '' }}> Jurídica        
        @error('type')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">

    <div class="col-sm-3">
        <label for="type">Cèd / Rif</label>
        <select class="form-control @error('letter') is-invalid @enderror" name="letter" id="letter" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>
            <option {{ isset($client) && substr($client->ced_rif,0,1)=="V" ? "selected" : null }}>V</option>
            <option {{ isset($client) && substr($client->ced_rif,0,1)=="E" ? "selected" : null }}>E</option>
            <option {{ isset($client) && substr($client->ced_rif,0,1)=="J" ? "selected" : null }}>J</option>
            <option {{ isset($client) && substr($client->ced_rif,0,1)=="G" ? "selected" : null }}>G</option>
            <option {{ isset($client) && substr($client->ced_rif,0,1)=="C" ? "selected" : null }}>C</option>
        </select>
    </div>
    <div class="col-sm-9">
        <label for="type">Nº</label>
        <input type="text" 
               class="form-control @error('ced_rif') is-invalid @enderror"
               id="cedrif"
               name="ced_rif"
               placeholder="Cédula o Rif"               
               value="{{ isset($client) && substr($client->ced_rif, 1, strlen($client->ced_rif)) 
                   ? substr($client->ced_rif, 1, strlen($client->ced_rif))                           
                   : substr(old('ced_rif'), 1, strlen(old('ced_rif'))) }}"
               {{ isset($readonly) ? "readonly" : null }}>
        @error('ced_rif')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <div class="col-sm-12">
        <label for="name">Nombre o razòn social del cliente:</label>
        <input type="text"
               class="form-control @error('business_name') is-invalid @enderror"
               id="business_name"
               name="business_name"
               value="{{ isset($client) && $client->business_name ? $client->business_name : old('business_name') }}"
               {{ isset($readonly) ? "readonly" : null }}>
        @error('business_name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="name">Teléfono o celular del cliente:</label>
        <input type="text"
               class="form-control @error('phone') is-invalid @enderror"
               id="phone"
               name="phone"
               value="{{ isset($client) && $client->phone ? $client->phone : old('phone') }}"
               {{ isset($readonly) ? "readonly" : null }}>
        @error('phone')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div><hr/><p>Direcciòn de Domicilio</p></div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="state">Estado:</label>
       
        <select class="form-control @error('state') is-invalid @enderror"
                id="state"
                name="state"
                onchange="municipalitySearch(this.value)" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>                             
            @foreach ($states as $state)
            <option value="{{ $state['id'] }}"
                {{ isset($client) && $state['id'] == $client->state ? "selected" : null }}>
                {{ $state['description'] }}
            </option>
            @endforeach            
        </select>
        @error('state')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="municipality">Municipio:</label>
        <select class="form-control @error('municipality') is-invalid @enderror"
                id="municipality"
                name="municipality"
                onchange="parishSearch(this.value)" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>            
            @foreach ($municipalities as $municipality)
            <option value="{{ $municipality['id'] }}"
                {{ isset($client) && $municipality['id'] == $client->municipality ? "selected" : null }}>
                {{ $municipality['description'] }}
            </option>
            @endforeach
        </select>
        @error('municipality')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="parish">Parroquia:</label>
        <select class="form-control @error('parish') is-invalid @enderror"
                id="parish"
                name="parish" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>
            @foreach ($parishes as $parish)
            <option value="{{ $parish['id'] }}"
                {{ isset($client) && $parish['id'] == $client->parish ? "selected" : null }}>
                {{ $parish['description'] }}
            </option>
            @endforeach
        </select>
        @error('parish')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="parish">Tipo de Zona:</label>
        <select class="form-control @error('zone_type') is-invalid @enderror"
                id="zone_type"
                name="zone_type" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>
            @foreach ($zoneTypes as $zoneType)
            <option value="{{ $zoneType['id'] }}"
                {{ isset($client) && $zoneType['id'] == $client->zone_type ? "selected" : null }}>
                {{ $zoneType['description'] }}
            </option>
            @endforeach
        </select>
        @error('zone_type')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label>Nombre Zona:</label>
        <input type="text" 
               class="form-control @error('zone_desc') is-invalid @enderror"
               id="zone_desc"
               name="zone_desc"               
               value="{{ isset($client) && $client->zone_desc ? $client->zone_desc : old('zone_desc') }}"
               {{ isset($readonly) ? "readonly" : null }}>
        @error('zone_desc')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="parish">Tipo de Calle:</label>
        <select class="form-control @error('route_type') is-invalid @enderror"
                id="route_type"
                name="route_type" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>
            @foreach ($routeTypes as $routeType)
            <option value="{{ $routeType['id'] }}"
                {{ isset($client) && $routeType['id'] == $client->route_type ? "selected" : null }}>
                {{ $routeType['description'] }}
            </option>
            @endforeach            
        </select>
        @error('route_type')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label>Nombre Calle:</label>
        <input type="text" 
               class="form-control @error('route_desc') is-invalid @enderror"
               id="route_desc"
               name="route_desc"
               value="{{ isset($client) && $client->route_desc ? $client->route_desc : old('route_desc') }}"
               {{ isset($readonly) ? "readonly" : null }}>
        @error('route_desc')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label for="domicile_type">Tipo de Domicilio:</label>
        <select class="form-control @error('domicile_type') is-invalid @enderror"
                id="domicile_type"
                name="domicile_type" {{ isset($readonly) ? "readonly" : null }}>
            <option>Seleccione...</option>
            @foreach ($domicileTypes as $domicileType)
            <option value="{{ $domicileType['id'] }}"
                {{ isset($client) && $domicileType['id'] == $client->domicile_type ? "selected" : null }}>
                {{ $domicileType['description'] }}
            </option>
            @endforeach 
        </select>
        @error('domicile_type')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
        <label>Nombre del Domicilio:</label>
        <input type="text"
               class="form-control @error('home_desc_desc') is-invalid @enderror"
               id="home_desc"
               name="domicile_desc"               
               value="{{ isset($client) && $client->domicile_desc ? $client->domicile_desc : old('domicile_desc') }}"
               {{ isset($readonly) ? "readonly" : null }}>
        @error('domicile_desc')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12">
    <label>Especifique</label>
        <textarea class="form-control @error('specification') is-invalid @enderror"
        id="specification"
        name="specification"
        rows="3"
        placeholder="Especificación"
        {{ isset($readonly) ? "readonly" : null }}>{{ isset($client) 
            && $client->specification 
            ? $client->specification
            : old('specification') }}
        </textarea>
        @error('specification')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

resources/views/clients/partials/modal_delete.blade.php
<div class="modal fade" id="{{ isset($modalId) ? $modalId : 'modalDelete' }}" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="{{ isset($modalId) ? $modalId : 'modalDeleteLabel' }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="{{ isset($modalId) ? $modalId : 'modalDeleteLabel' }}">Eliminar Usario</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ¿Está seguro de eliminar a este usuario?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form method="POST" action="{{ route('client.destroy', $client['email']) }}">
            @method('DELETE')
            @csrf
            <button class="btn btn-primary font-weight-bold">Eliminar</button>
          </form>
        </div>
      </div>
    </div>
  </div>